version: "3.9"

services:
  npm:
    image: jc21/nginx-proxy-manager:${NPM_TAG:-latest}
    container_name: npm
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${ADMIN_PORT}:81"
    volumes:
      - ${STORAGE_ROOT}/data:/data
      - ${STORAGE_ROOT}/certs:/etc/letsencrypt
    environment:
      - TZ=${TZ}{TZ}