version: '3.9'
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    environment:
      PGID: '3000'
      TZ: America/Los_Angeles
      PUID: '3001'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      NODE_VERSION: 20.20.1
      YARN_VERSION: 1.22.22
      PORT: '80'
      NODE_ENV: production
      CONFIG_PATH: /config
      METADATA_PATH: /metadata
      SOURCE: docker
      NUSQLITE3_DIR: /usr/local/lib/nusqlite3
      NUSQLITE3_PATH: /usr/local/lib/nusqlite3/libnusqlite3.so
    ports:
    - 13378:80/tcp
    networks: book-stack_books_net
    volumes:
    - ${DATA_PATH}:/config:rw
    - ${DATA_PATH}:/metadata:rw
    - ${DATA_PATH}:/audiobooks:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  book-stack_books_net:
    external: true
