services:
  open_speed_test:
    image: "openspeedtest/latest:v2.0.6"
    container_name: "ix-open-speed-test-open-speed-test-1"
    environment:
      TZ: America/Los_Angeles
      UMASK: 002
      UMASK_SET: 002
      CHANGE_CONTAINER_PORTS: True
      HTTPS_PORT: 30117
      HTTP_PORT: 30116
      NGINX_VERSION: 1.26.2
      PKG_RELEASE: 1
      DYNPKG_RELEASE: 2
      NJS_VERSION: 0.8.5
      NJS_RELEASE: 1
      ENABLE_LETSENCRYPT: false
      DOMAIN_NAME: false
      USER_EMAIL: false
      CONFIG: /etc/nginx/conf.d/OpenSpeedTest-Server.conf
      INDEX_HTML: /usr/share/nginx/html/index.html
      SET_USER: 101
    ports:
      - "30116:30116"
      - "30117:30117"
    volumes:
      - ${DATA_PATH}:/var/log/letsencrypt
    restart: "unless-stopped"
    networks:
      - open-speed-test