version: '3.9'
services:
  stirling-pdf-stack-stirling-pdf-1:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf-stack-stirling-pdf-1
    restart: unless-stopped
    environment:
      SERVER_PORT: '8080'
      PASSWORD: ${PASSWORD}
      ALLOWED_HOSTS: ${STIRLING_DOMAIN},${PUBLIC_IP},${HOST_IP}
      PASSWORD_PROTECT: 'true'
      SECURITY_ENABLELOGIN: 'true'
      LANGS: en_GB
      USERNAME: Gaurav
      DOCKER_ENABLE_SECURITY: 'false'
      PATH: /opt/venv/bin:/opt/unoserver-venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      DEBIAN_FRONTEND: noninteractive
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      TESS_BASE_PATH: /usr/share/tesseract-ocr/5/tessdata
      VERSION_TAG: 2.5.3
      JAVA_BASE_OPTS: -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/configs/heap_dumps -XX:+UnlockExperimentalVMOptions -XX:MaxRAMPercentage=75
        -XX:InitiatingHeapOccupancyPercent=20 -XX:+G1PeriodicGCInvokesConcurrent -XX:G1PeriodicGCInterval=10000
        -XX:+UseStringDeduplication -XX:G1PeriodicGCSystemLoadThreshold=70 -Djava.awt.headless=true
      JAVA_CUSTOM_OPTS: ''
      HOME: /home/stirlingpdfuser
      PUID: '1000'
      PGID: '1000'
      UMASK: '022'
      UNO_PATH: /usr/lib/libreoffice/program
      LIBREOFFICE_BIN_PATH: /usr/lib/libreoffice/program/soffice.bin
      STIRLING_TEMPFILES_DIRECTORY: /tmp/stirling-pdf
      TMPDIR: /tmp/stirling-pdf
      TEMP: /tmp/stirling-pdf
      TMP: /tmp/stirling-pdf
      QT_QPA_PLATFORM: offscreen
      QTWEBENGINE_CHROMIUM_FLAGS: --disable-gpu --disable-dev-shm-usage
    ports:
    - 8084:8080/tcp
    networks: stirling-pdf-stack_default
    volumes:
    - ${DATA_PATH}:/usr/share/tessdata:rw
    - ${DATA_PATH}:/configs:rw
    - ${DATA_PATH}:/output:rw
    - ${DATA_PATH}:/logs:rw
    - ${DATA_PATH}:/pipeline:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  stirling-pdf-stack_default:
    external: true
