version: '3.9'
services:
  ix-invoice-ninja-scheduler-1:
    image: invoiceninja/invoiceninja-octane:5.12.28-o
    container_name: ix-invoice-ninja-scheduler-1
    restart: unless-stopped
    environment:
      DB_HOST: mariadb
      PDF_GENERATOR: snappdf
      IN_USER_EMAIL: ${USER_EMAIL}
      IS_DOCKER: 'true'
      UMASK_SET: '002'
      NVIDIA_VISIBLE_DEVICES: void
      LARAVEL_ROLE: scheduler
      SESSION_DRIVER: redis
      TZ: Etc/UTC
      APP_URL: https://${INVOICE_DOMAIN}
      REDIS_USERNAME: default
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REQUIRE_HTTPS: 'false'
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_CACHE_DB: '1'
      FILESYSTEM_DISK: debian_docker
      APP_KEY: ${APP_KEY}
      IN_PASSWORD: ${IN_PASSWORD}
      UMASK: '002'
      REDIS_HOST: redis
      QUEUE_CONNECTION: redis
      PHANTOMJS_PDF_GENERATION: 'false'
      APP_ENV: production
      REDIS_PORT: '6379'
      DB_CONNECTION: mysql
      DB_DATABASE: ninja
      DB_PORT: '3306'
      DB_USERNAME: ninja
      REDIS_DB: '0'
      CACHE_DRIVER: redis
      SCOUT_DRIVER: None
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PHPIZE_DEPS: "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\
        \tmake \t\tpkg-config \t\tre2c"
      PHP_INI_DIR: /usr/local/etc/php
      PHP_CFLAGS: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
      PHP_CPPFLAGS: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
      PHP_LDFLAGS: -Wl,-O1 -pie
      GPG_KEYS: ${GPG_KEYS}
      PHP_VERSION: 8.4.13
      PHP_URL: https://www.php.net/distributions/php-8.4.13.tar.xz
      PHP_ASC_URL: https://www.php.net/distributions/php-8.4.13.tar.xz.asc
      PHP_SHA256: b4f27adf30bcf262eacf93c78250dd811980f20f3b90d79a3dc11248681842df
      XDG_CONFIG_HOME: /config
      XDG_DATA_HOME: /data
      GODEBUG: cgocheck=0
    networks: ix-invoice-ninja_ix-internal-invoice-ninja-net
    healthcheck:
      test:
      - CMD
      - pgrep
      - -f
      - schedule:work
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  ix-invoice-ninja-worker-1:
    image: invoiceninja/invoiceninja-octane:5.12.28-o
    container_name: ix-invoice-ninja-worker-1
    restart: unless-stopped
    environment:
      UMASK_SET: '002'
      LARAVEL_ROLE: worker
      TZ: Etc/UTC
      APP_ENV: production
      NVIDIA_VISIBLE_DEVICES: void
      PDF_GENERATOR: snappdf
      APP_URL: https://${INVOICE_DOMAIN}
      REDIS_USERNAME: default
      REQUIRE_HTTPS: 'false'
      PHANTOMJS_PDF_GENERATION: 'false'
      REDIS_DB: '0'
      DB_DATABASE: ninja
      SESSION_DRIVER: redis
      REDIS_CACHE_DB: '1'
      FILESYSTEM_DISK: debian_docker
      SCOUT_DRIVER: None
      DB_CONNECTION: mysql
      DB_PORT: '3306'
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_PORT: '6379'
      REDIS_HOST: redis
      IN_USER_EMAIL: ${USER_EMAIL}
      CACHE_DRIVER: redis
      APP_KEY: ${APP_KEY}
      DB_USERNAME: ninja
      IN_PASSWORD: ${IN_PASSWORD}
      IS_DOCKER: 'true'
      QUEUE_CONNECTION: redis
      UMASK: '002'
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DB_HOST: mariadb
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PHPIZE_DEPS: "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\
        \tmake \t\tpkg-config \t\tre2c"
      PHP_INI_DIR: /usr/local/etc/php
      PHP_CFLAGS: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
      PHP_CPPFLAGS: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
      PHP_LDFLAGS: -Wl,-O1 -pie
      GPG_KEYS: ${GPG_KEYS}
      PHP_VERSION: 8.4.13
      PHP_URL: https://www.php.net/distributions/php-8.4.13.tar.xz
      PHP_ASC_URL: https://www.php.net/distributions/php-8.4.13.tar.xz.asc
      PHP_SHA256: b4f27adf30bcf262eacf93c78250dd811980f20f3b90d79a3dc11248681842df
      XDG_CONFIG_HOME: /config
      XDG_DATA_HOME: /data
      GODEBUG: cgocheck=0
    networks: ix-invoice-ninja_ix-internal-invoice-ninja-net
    healthcheck:
      test:
      - CMD
      - pgrep
      - -f
      - queue:work
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  ix-invoice-ninja-invoice-ninja-1:
    image: invoiceninja/invoiceninja-octane:5.12.28-o
    container_name: ix-invoice-ninja-invoice-ninja-1
    restart: unless-stopped
    environment:
      REDIS_USERNAME: default
      TZ: Etc/UTC
      FILESYSTEM_DISK: debian_docker
      IN_USER_EMAIL: ${USER_EMAIL}
      SESSION_DRIVER: redis
      UMASK: '002'
      DB_PASSWORD: ${DB_PASSWORD}
      UMASK_SET: '002'
      DB_DATABASE: ninja
      DB_HOST: mariadb
      IN_PASSWORD: ${IN_PASSWORD}
      APP_ENV: production
      REDIS_HOST: redis
      DB_USERNAME: ninja
      SCOUT_DRIVER: None
      PDF_GENERATOR: snappdf
      IS_DOCKER: 'true'
      APP_KEY: ${APP_KEY}
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_CACHE_DB: '1'
      REQUIRE_HTTPS: 'false'
      PHANTOMJS_PDF_GENERATION: 'false'
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      LARAVEL_ROLE: app
      REDIS_DB: '0'
      DB_PORT: '3306'
      DB_CONNECTION: mysql
      REDIS_PORT: '6379'
      APP_URL: https://${INVOICE_DOMAIN}
      NVIDIA_VISIBLE_DEVICES: void
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PHPIZE_DEPS: "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\
        \tmake \t\tpkg-config \t\tre2c"
      PHP_INI_DIR: /usr/local/etc/php
      PHP_CFLAGS: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
      PHP_CPPFLAGS: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
      PHP_LDFLAGS: -Wl,-O1 -pie
      GPG_KEYS: ${GPG_KEYS}
      PHP_VERSION: 8.4.13
      PHP_URL: https://www.php.net/distributions/php-8.4.13.tar.xz
      PHP_ASC_URL: https://www.php.net/distributions/php-8.4.13.tar.xz.asc
      PHP_SHA256: b4f27adf30bcf262eacf93c78250dd811980f20f3b90d79a3dc11248681842df
      XDG_CONFIG_HOME: /config
      XDG_DATA_HOME: /data
      GODEBUG: cgocheck=0
    ports:
    - 31105:31105/tcp
    networks: ix-invoice-ninja_ix-internal-invoice-ninja-net
    healthcheck:
      test:
      - CMD
      - curl
      - --request
      - GET
      - --silent
      - --output
      - /dev/null
      - --show-error
      - --fail
      - http://127.0.0.1:31105/health
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  ix-invoice-ninja-mariadb-1:
    image: mariadb:12.2.2
    container_name: ix-invoice-ninja-mariadb-1
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ninja
      MARIADB_USER: ninja
      NVIDIA_VISIBLE_DEVICES: void
      UMASK_SET: '002'
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_AUTO_UPGRADE: 'true'
      UMASK: '002'
      TZ: Etc/UTC
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      GOSU_VERSION: '1.19'
      LANG: C.UTF-8
      MARIADB_VERSION: 1:12.2.2+maria~ubu2404
    networks: ix-invoice-ninja_ix-internal-invoice-ninja-net
    healthcheck:
      test:
      - CMD
      - mariadb-admin
      - --user=root
      - --host=127.0.0.1
      - --port=3306
      - --password=${DB_PASSWORD}
      - ping
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  ix-invoice-ninja-redis-1:
    image: valkey/valkey:9.0.3
    container_name: ix-invoice-ninja-redis-1
    restart: unless-stopped
    environment:
      UMASK_SET: '002'
      NVIDIA_VISIBLE_DEVICES: void
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TZ: Etc/UTC
      UMASK: '002'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      VALKEY_VERSION: ${VALKEY_VERSION}
    networks: ix-invoice-ninja_ix-internal-invoice-ninja-net
    healthcheck:
      test:
      - CMD
      - redis-cli
      - -h
      - 127.0.0.1
      - -p
      - '6379'
      - -a
      - whiteknight009
      - ping
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  ix-invoice-ninja_ix-internal-invoice-ninja-net:
    external: true
