version: "3.9"

services:
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped

    network_mode: host

    volumes:
      - /mnt/storagepool/apps_config/matter-server:/data

    environment:
      - TZ=${TZ}