version: "3.8"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped

    environment:
      - PUID=3001
      - PGID=3000
      - TZ=America/Los_Angeles
      - VERSION=docker
      - PLEX_CLAIM=claim-9ZdKBMn64pr44GK7EdaM

    volumes:
      - /path/to/your/data:/config
      - /path/to/your/data:/transcode
      - /path/to/your/data:/media

    ports:
      - "32400:32400"
    devices:
      # Optional â enable ONLY if you plan to use hardware transcoding
      - /dev/dri:/dev/dri