version: '3.9'
services:
  postgres-bitmagnet:
    image: postgres:16
    container_name: postgres-bitmagnet
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: bitmagnet
      POSTGRES_USER: bitmagnet
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/16/bin
      GOSU_VERSION: '1.19'
      LANG: en_US.utf8
      PG_MAJOR: '16'
      PG_VERSION: 16.13-1.pgdg13+1
      PGDATA: /var/lib/postgresql/data
    volumes:
    - ${DATA_PATH}:/var/lib/postgresql/data:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks: {}
