version: "3.9"

services:
  metube:
    image: ghcr.io/alexta69/metube:${METUBE_TAG:-latest}
    container_name: metube
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - ${MEDIA_ROOT}:/downloads:rw
      - ${STORAGE_ROOT}/state:/downloads/.metube:rw
    environment:
      - UID=changeme
      - GID=changeme
      - DOWNLOAD_DIR=changeme
      - STATE_DIR=changeme
      - YTDL_OPTIONS=changeme