version: '3.9'
services:
  metube:
    image: ghcr.io/alexta69/metube:latest
    container_name: metube
    restart: unless-stopped
    environment:
      YTDL_OPTIONS: '{"writethumbnail":true,"convertthumbnails":"jpg"}'
      UID: '3001'
      GID: '3000'
      DOWNLOAD_DIR: /downloads
      STATE_DIR: /downloads/.metube
      PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      GPG_KEY: ${GPG_KEY}
      PYTHON_VERSION: 3.13.12
      PYTHON_SHA256: 2a84cd31dd8d8ea8aaff75de66fc1b4b0127dd5799aa50a64ae9a313885b4593
      PUID: '1000'
      PGID: '1000'
      UMASK: '022'
      TEMP_DIR: /downloads
      METUBE_VERSION: 2026.03.08
    ports:
    - 8086:8081/tcp
    networks: metube-stack_default
    volumes:
    - ${DATA_PATH}:/downloads:rw
    - ${DATA_PATH}:/downloads/.metube:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  metube-stack_default:
    external: true
