version: '3.9'
services:
  ix-homebox-homebox-1:
    image: ghcr.io/sysadminsmedia/homebox:0.24.2-rootless
    container_name: ix-homebox-homebox-1
    restart: unless-stopped
    environment:
      HBOX_WEB_PORT: '30149'
      HBOX_STORAGE_DATA: /data
      NVIDIA_VISIBLE_DEVICES: void
      HBOX_MODE: production
      UID: '568'
      USER_ID: '568'
      GROUP_ID: '568'
      TZ: America/Los_Angeles
      GID: '568'
      PUID: '568'
      UMASK_SET: '002'
      PGID: '568'
      UMASK: '002'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      HBOX_STORAGE_CONN_STRING: file:///?no_tmp_dir=true
      HBOX_STORAGE_PREFIX_PATH: data
      HBOX_DATABASE_SQLITE_PATH: /data/homebox.db?_pragma=busy_timeout=2000&_pragma=journal_mode=WAL&_fk=1&_time_format=sqlite
    ports:
    - 30149:30149/tcp
    networks: ix-homebox_default
    healthcheck:
      test:
      - CMD
      - wget
      - --quiet
      - -O
      - /dev/null
      - http://127.0.0.1:30149/api/v1/status
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  ix-homebox_default:
    external: true
