version: '3.9'
services:
  bookshelf:
    image: ghcr.io/pennydreadful/bookshelf:hardcover
    container_name: bookshelf
    restart: unless-stopped
    environment:
      PUID: '3001'
      PGID: '3000'
      TZ: America/Los_Angeles
      PATH: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PS1: '$(whoami)@$(hostname):$(pwd)\$ '
      HOME: /root
      TERM: xterm
      S6_CMD_WAIT_FOR_SERVICES_MAXTIME: '0'
      S6_VERBOSITY: '1'
      S6_STAGE2_HOOK: /docker-mods
      VIRTUAL_ENV: /lsiopy
      XDG_CONFIG_HOME: /config/xdg
      COMPlus_EnableDiagnostics: '0'
      TMPDIR: /run/readarr-temp
      METADATA_URL: https://hardcover.bookinfo.pro
      HARDCOVER: 'true'
    ports:
    - 8787:8787/tcp
    networks: book-stack_default
    volumes:
    - ${DATA_PATH}:/config:rw
    - ${DATA_PATH}:/downloads/torrents:rw
    - ${DATA_PATH}:/downloads/usenet:rw
    - ${DATA_PATH}:/ebooks:rw
    - ${DATA_PATH}:/audiobooks:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  book-stack_default:
    external: true
