version: '3.9'
services:
  portainer_portainer_1:
    image: portainer/portainer-ce:2.40.0
    container_name: ix-portainer-portainer-1
    restart: unless-stopped
    environment:
      UMASK_SET: '002'
      UID: '568'
      USER_ID: '568'
      TZ: Etc/UTC
      GROUP_ID: '568'
      NVIDIA_VISIBLE_DEVICES: void
      PUID: '568'
      GID: '568'
      UMASK: '002'
      PGID: '568'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
    - 31015:31015/tcp
    - 31016:31016/tcp
    networks:
    - ix-portainer_default
    healthcheck:
      test:
      - NONE
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  ix-portainer_default:
    external: true
