services:
  paperless_ai:
    image: "clusterzx/paperless-ai:3.0.9"
    container_name: "ix-paperless-ai-paperless-1"
    environment:
      TZ: America/Los_Angeles
      UMASK: 002
      UMASK_SET: 002
      NODE_ENV: production
      PAPERLESS_AI_PORT: 30226
      NODE_VERSION: 22.21.1
      YARN_VERSION: 1.22.22
    ports:
      - "30226:30226"
    volumes:
      - ${DATA_PATH}:/app/data
    restart: "unless-stopped"
    networks:
      - paperless-ai