version: "3.8"

services:
  db:
    image: postgres:${PG_TAG:-15}
    container_name: vaultwarden-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}{POSTGRES_PASSWORD}
    volumes:
      - ${STORAGE_ROOT}/postgres:/var/lib/postgresql/data
    networks:
      - vaultwarden-net

  vaultwarden:
    image: vaultwarden/server:${VW_TAG:-latest}
    container_name: vaultwarden
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_TOKEN=${ADMIN_TOKEN}{ADMIN_TOKEN}
      ROCKET_PORT: ${ROCKET_PORT}
      DOMAIN: ${DOMAIN}
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
    ports:
      - "${HOST_PORT}:${ROCKET_PORT}"
    volumes:
      - ${STORAGE_ROOT}/data:/data
    networks:
      - vaultwarden-net

networks:
  vaultwarden-net:
    driver: bridge