version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped

    ports:
      - 5678:5678

    environment:
      - TZ=America/Los_Angeles

      - N8N_HOST=n3n.gsynch.com
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n3n.gsynch.com
      - N8N_PORT=5678
      - N8N_TRUST_PROXY=true

      - N8N_SECURE_COOKIE=false
      - N8N_AI_ENABLED=true
      - N8N_ENABLE_COMMUNITY_NODES=true

      - N8N_ALLOW_FILE_ACCESS=/data
      - N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES=false
      - GENERIC_TIMEZONE=America/Los_Angeles

    volumes:
      - /path/to/your/data/apps_config/n8n/portainer:/home/node/.n8n
      - /path/to/your/data/master/n8n/know_base:/home/node/.n8n-files