version: "3.9"

services:
  db:
    image: postgres:${PG_TAG:-15}
    container_name: wygiwyh-db
    hostname: wygiwyh-db
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_USER: changeme
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: changeme
    volumes:
      - ${STORAGE_ROOT}/db:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 45s
      retries: 10
    restart: on-failure:5

  wygiwyh:
    image: eitchtee/wygiwyh:${KK_TAG:-latest}
    container_name: wygiwyh
    command: /start-single
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    environment:
      TZ: ${TZ}
      DEBUG: changeme
      URL: changeme
      HTTPS_ENABLED: changeme
      SECRET_KEY: your-api-key-here
      DJANGO_ALLOWED_HOSTS: changeme
      OUTBOUND_PORT: changeme
      ADMIN_EMAIL: changeme
      ADMIN_PASSWORD: changeme
      SQL_DATABASE: changeme
      SQL_USER: changeme
      SQL_PASSWORD: changeme
      SQL_HOST: wygiwyh-db
      SQL_PORT: 5432
      WEB_CONCURRENCY: changeme
      ENABLE_SOFT_DELETE: changeme
      KEEP_DELETED_TRANSACTIONS_FOR: changeme
      TASK_WORKERS: changeme
    volumes:
      - ${STORAGE_ROOT}/media:/app/media:rw
      - ${STORAGE_ROOT}/static:/app/static:rw
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/${CONTAINER_PORT}' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    restart: on-failure:5