version: "3.9"

services:
  db:
    image: postgres:${PG_TAG:-15}
    container_name: wygiwyh-db
    hostname: wygiwyh-db
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}{POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${STORAGE_ROOT}/db:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 45s
      retries: 10
    restart: on-failure:5

  wygiwyh:
    image: eitchtee/wygiwyh:${KK_TAG:-latest}
    container_name: wygiwyh
    command: /start-single
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    environment:
      TZ=${TZ}{TZ}
      DEBUG: ${DEBUG}
      URL: ${APP_URL}
      HTTPS_ENABLED: ${HTTPS_ENABLED}
      SECRET_KEY=${SECRET_KEY}{SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      OUTBOUND_PORT: ${OUTBOUND_PORT}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD=${ADMIN_PASSWORD}{ADMIN_PASSWORD}
      SQL_DATABASE: ${POSTGRES_DB}
      SQL_USER: ${POSTGRES_USER}
      SQL_PASSWORD=${SQL_PASSWORD}{POSTGRES_PASSWORD}
      SQL_HOST: wygiwyh-db
      SQL_PORT: 5432
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      ENABLE_SOFT_DELETE: ${ENABLE_SOFT_DELETE}
      KEEP_DELETED_TRANSACTIONS_FOR: ${KEEP_DAYS}
      TASK_WORKERS: ${WORKERS}
    volumes:
      - ${STORAGE_ROOT}/media:/app/media:rw
      - ${STORAGE_ROOT}/static:/app/static:rw
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/${CONTAINER_PORT}' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    restart: on-failure:5