version: '3.9'
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    environment:
      DNS_KEEP_NAMESERVER: 'off'
      CONTROL_SERVER_ADDRESS: :8000
      DNS_ADDRESS: 1.1.1.1
      DOT: 'on'
      FIREWALL_INPUT_PORTS: 8085,6881,3333,8089,8080
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      VPN_TYPE: wireguard
      FIREWALL: 'on'
      FIREWALL_OUTBOUND_SUBNETS: ${HOST_IP}/24
      TZ: America/Los_Angeles
      VPN_SERVICE_PROVIDER: nordvpn
      BLOCK_MALICIOUS: 'on'
      SERVER_COUNTRIES: United States
      HEALTH_TARGET_ADDRESS: cloudflare.com:443
      BLOCK_IPV6: 'on'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      VPN_INTERFACE: tun0
      OPENVPN_ENDPOINT_IP: ''
      OPENVPN_ENDPOINT_PORT: ''
      OPENVPN_PROTOCOL: udp
      OPENVPN_USER: ''
      OPENVPN_PASSWORD: ''
      OPENVPN_USER_SECRETFILE: ${OPENVPN_USER_SECRETFILE}
      OPENVPN_PASSWORD_SECRETFILE: ${OPENVPN_PASSWORD_SECRETFILE}
      OPENVPN_VERSION: '2.6'
      OPENVPN_VERBOSITY: '1'
      OPENVPN_FLAGS: ''
      OPENVPN_CIPHERS: ''
      OPENVPN_AUTH: ''
      OPENVPN_PROCESS_USER: root
      OPENVPN_MSSFIX: ''
      OPENVPN_CUSTOM_CONFIG: ''
      WIREGUARD_ENDPOINT_IP: ''
      WIREGUARD_ENDPOINT_PORT: ''
      WIREGUARD_CONF_SECRETFILE: ${WIREGUARD_CONF_SECRETFILE}
      WIREGUARD_PRIVATE_KEY_SECRETFILE: ${WIREGUARD_PRIVATE_KEY_SECRETFILE}
      WIREGUARD_PRESHARED_KEY: ''
      WIREGUARD_PRESHARED_KEY_SECRETFILE: ${WIREGUARD_PRESHARED_KEY_SECRETFILE}
      WIREGUARD_PUBLIC_KEY: ''
      WIREGUARD_ALLOWED_IPS: ''
      WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: '0'
      WIREGUARD_ADDRESSES: ''
      WIREGUARD_ADDRESSES_SECRETFILE: ${WIREGUARD_ADDRESSES_SECRETFILE}
      WIREGUARD_MTU: ''
      WIREGUARD_IMPLEMENTATION: auto
      AMNEZIAWG_ENDPOINT_IP: ''
      AMNEZIAWG_ENDPOINT_PORT: ''
      AMNEZIAWG_CONF_SECRETFILE: ${AMNEZIAWG_CONF_SECRETFILE}
      AMNEZIAWG_PRIVATE_KEY: ''
      AMNEZIAWG_PRIVATE_KEY_SECRETFILE: ${AMNEZIAWG_PRIVATE_KEY_SECRETFILE}
      AMNEZIAWG_PRESHARED_KEY: ''
      AMNEZIAWG_PRESHARED_KEY_SECRETFILE: ${AMNEZIAWG_PRESHARED_KEY_SECRETFILE}
      AMNEZIAWG_PUBLIC_KEY: ''
      AMNEZIAWG_ALLOWED_IPS: ''
      AMNEZIAWG_PERSISTENT_KEEPALIVE_INTERVAL: '0'
      AMNEZIAWG_ADDRESSES: ''
      AMNEZIAWG_ADDRESSES_SECRETFILE: ${AMNEZIAWG_ADDRESSES_SECRETFILE}
      AMNEZIAWG_MTU: ''
      AMNEZIAWG_JC: '0'
      AMNEZIAWG_JMIN: '0'
      AMNEZIAWG_JMAX: '0'
      AMNEZIAWG_S1: '0'
      AMNEZIAWG_S2: '0'
      AMNEZIAWG_S3: '0'
      AMNEZIAWG_S4: '0'
      AMNEZIAWG_H1: ''
      AMNEZIAWG_H2: ''
      AMNEZIAWG_H3: ''
      AMNEZIAWG_H4: ''
      AMNEZIAWG_I1: ''
      AMNEZIAWG_I2: ''
      AMNEZIAWG_I3: ''
      AMNEZIAWG_I4: ''
      AMNEZIAWG_I5: ''
      VPN_PORT_FORWARDING: 'off'
      VPN_PORT_FORWARDING_PROVIDER: ''
      VPN_PORT_FORWARDING_UP_COMMAND: ''
      VPN_PORT_FORWARDING_DOWN_COMMAND: ''
      VPN_PORT_FORWARDING_LISTENING_PORTS: '0'
      VPN_PORT_FORWARDING_PORTS_COUNT: '1'
      VPN_PORT_FORWARDING_STATUS_FILE: /tmp/gluetun/forwarded_port
      PMTUD_ICMP_ADDRESSES: 1.1.1.1,8.8.8.8
      PMTUD_TCP_ADDRESSES: 1.1.1.1:443,8.8.8.8:443,1.1.1.1:53,8.8.8.8:53,[2606:4700:4700::1111]:53,[2001:4860:4860::8888]:53,[2606:4700:4700::1111]:443,[2001:4860:4860::8888]:443
      SERVER_REGIONS: ''
      SERVER_CITIES: ''
      SERVER_HOSTNAMES: ''
      SERVER_CATEGORIES: ''
      ISP: ''
      OWNED_ONLY: 'no'
      PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET: ''
      VPN_PORT_FORWARDING_USERNAME: ''
      VPN_PORT_FORWARDING_PASSWORD: ''
      OPENVPN_CERT: ''
      OPENVPN_KEY: ''
      OPENVPN_CLIENTCRT_SECRETFILE: ${OPENVPN_CLIENTCRT_SECRETFILE}
      OPENVPN_CLIENTKEY_SECRETFILE: ${OPENVPN_CLIENTKEY_SECRETFILE}
      OPENVPN_ENCRYPTED_KEY: ''
      OPENVPN_ENCRYPTED_KEY_SECRETFILE: ${OPENVPN_ENCRYPTED_KEY_SECRETFILE}
      OPENVPN_KEY_PASSPHRASE: ''
      OPENVPN_KEY_PASSPHRASE_SECRETFILE: ${OPENVPN_KEY_PASSPHRASE_SECRETFILE}
      SERVER_NUMBER: ''
      SERVER_NAMES: ''
      STREAM_ONLY: ''
      FREE_ONLY: ''
      SECURE_CORE_ONLY: ''
      TOR_ONLY: ''
      MULTIHOP_ONLY: ''
      PREMIUM_ONLY: ''
      PORT_FORWARD_ONLY: ''
      FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT: 'on'
      FIREWALL_VPN_INPUT_PORTS: ''
      FIREWALL_IPTABLES_LOG_LEVEL: info
      IPV6_CHECK_ADDRESSES: '[2001:4860:4860::8888]:53,[2606:4700:4700::1111]:53'
      LOG_LEVEL: info
      HEALTH_SERVER_ADDRESS: 127.0.0.1:9999
      HEALTH_TARGET_ADDRESSES: cloudflare.com:443,github.com:443
      HEALTH_ICMP_TARGET_IPS: 1.1.1.1,8.8.8.8
      HEALTH_SMALL_CHECK_TYPE: icmp
      HEALTH_RESTART_VPN: 'on'
      DNS_UPSTREAM_RESOLVER_TYPE: DoT
      DNS_UPSTREAM_RESOLVERS: ''
      DNS_BLOCK_IPS: ''
      DNS_BLOCK_IP_PREFIXES: ''
      DNS_CACHING: 'on'
      DNS_UPSTREAM_IPV6: 'off'
      BLOCK_SURVEILLANCE: 'off'
      BLOCK_ADS: 'off'
      DNS_UNBLOCK_HOSTNAMES: ''
      DNS_REBINDING_PROTECTION_EXEMPT_HOSTNAMES: ''
      DNS_UPDATE_PERIOD: 24h
      DNS_UPSTREAM_PLAIN_ADDRESSES: ''
      HTTPPROXY: ''
      HTTPPROXY_LOG: 'off'
      HTTPPROXY_LISTENING_ADDRESS: :8888
      HTTPPROXY_STEALTH: 'off'
      HTTPPROXY_USER: ''
      HTTPPROXY_PASSWORD: ''
      HTTPPROXY_USER_SECRETFILE: ${HTTPPROXY_USER_SECRETFILE}
      HTTPPROXY_PASSWORD_SECRETFILE: ${HTTPPROXY_PASSWORD_SECRETFILE}
      SHADOWSOCKS: 'off'
      SHADOWSOCKS_LOG: 'off'
      SHADOWSOCKS_LISTENING_ADDRESS: :8388
      SHADOWSOCKS_PASSWORD: ''
      SHADOWSOCKS_PASSWORD_SECRETFILE: ${SHADOWSOCKS_PASSWORD_SECRETFILE}
      SHADOWSOCKS_CIPHER: chacha20-ietf-poly1305
      HTTP_CONTROL_SERVER_LOG: 'on'
      HTTP_CONTROL_SERVER_ADDRESS: :8000
      HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH: ${HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH}
      HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: ${HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE}
      UPDATER_PERIOD: '0'
      UPDATER_MIN_RATIO: '0.8'
      UPDATER_VPN_SERVICE_PROVIDERS: ''
      UPDATER_PROTONVPN_EMAIL: ''
      UPDATER_PROTONVPN_PASSWORD: ''
      PUBLICIP_FILE: /tmp/gluetun/ip
      PUBLICIP_ENABLED: 'on'
      PUBLICIP_API: ipinfo,ifconfigco,ip2location,cloudflare
      PUBLICIP_API_TOKEN: ''
      STORAGE_FILEPATH: /gluetun/servers.json
      PPROF_ENABLED: 'no'
      PPROF_BLOCK_PROFILE_RATE: '0'
      PPROF_MUTEX_PROFILE_RATE: '0'
      PPROF_HTTP_SERVER_ADDRESS: :6060
      VERSION_INFORMATION: 'on'
      BORINGPOLL_GLUETUNCOM: 'off'
      PUID: '1000'
      PGID: '1000'
    ports:
    - 3333:3333/tcp
    - 6881:6881/tcp
    - 6881:6881/udp
    - 8089:8080/tcp
    - 8085:8085/tcp
    networks: arrnet
    volumes:
    - ${DATA_PATH}:/gluetun:rw
    healthcheck:
      test:
      - CMD-SHELL
      - /gluetun-entrypoint healthcheck
      interval: 5000000000
      timeout: 5000000000
      retries: 3
    logging:
      driver: gelf
      options:
        gelf-address: udp://${HOST_IP}:12201
        tag: '{{.Name}}'
networks:
  arrnet:
    external: true
