version: '3.9'
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    restart: unless-stopped
    environment:
      SYNC_GRAVITY_AD_LIST: 'true'
      SYNC_CONFIG_DNS: 'true'
      CRON: '*/15 * * * *'
      REPLICAS: http://100.74.68.110:3000|Ellipsis
      SYNC_GRAVITY_AD_LIST_BY_GROUP: 'true'
      SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP: 'true'
      PRIMARY: http://${HOST_IP}:3000|Ellipsis007!
      FULL_SYNC: 'false'
      SYNC_GRAVITY_DOMAIN_LIST: 'true'
      RUN_GRAVITY: 'false'
      TZ: America/Los_Angeles
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      API_ENABLED: 'true'
    networks: nebula-sync-stack_default
    volumes:
    - ${DATA_PATH}:/app/env:ro
    - ${DATA_PATH}:/app/logs:rw
    healthcheck:
      test:
      - CMD
      - nebula-sync
      - healthcheck
      interval: 30000000000
      timeout: 3000000000
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  nebula-sync-stack_default:
    external: true
