version: "3.8"

services:
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    restart: unless-stopped
    network_mode: host

    environment:
      - TZ=America/Los_Angeles

    volumes:
      - /path/to/your/data:/opt/unbound/etc/unbound

    healthcheck:
      test: ["CMD-SHELL", "drill @127.0.0.1 -p 5335 google.com || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s