services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:latest
    container_name: dispatcharr
    restart: unless-stopped
    volumes:
      - /mnt/storagepool/apps_config/dispatcharr/data:/data
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}{SECRET_KEY}
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info
    network_mode: "service:gluetun-iptv"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      
  gluetun-iptv:
    image: qmcgaw/gluetun
    container_name: gluetun-iptv
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=ZQc8ybf6n4hEEpmH97DvBDeQ
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CITIES=San Francisco
      - SERVER_SELECTION=fastest
      - TZ=${TZ}
      - DNS_ADDRESS=1.1.1.1
      - DOT=off
    ports:
      - 9191:9191
    volumes:
      - /mnt/storagepool/apps_config/gluetun-iptv:/gluetun-iptv
    restart: unless-stopped