version: "3.9"

services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:v1.16.4
    container_name: arcane
    ports:
      - "8055:8080"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /path/to/arcane:/data
    restart: unless-stopped
