version: '3.9'
services:
  scrutiny_scrutiny_1:
    image: ghcr.io/analogj/scrutiny:v0.8.6-omnibus
    container_name: ix-scrutiny-scrutiny-1
    restart: unless-stopped
    environment:
      TZ: Etc/UTC
      SCRUTINY_WEB_INFLUXDB_HOST: 127.0.0.1
      SCRUTINY_WEB_DATABASE_LOCATION: /opt/scrutiny/config/scrutiny.db
      UMASK: '002'
      SCRUTINY_WEB_LISTEN_PORT: '8080'
      SCRUTINY_WEB_LISTEN_HOST: 0.0.0.0
      NVIDIA_VISIBLE_DEVICES: void
      UMASK_SET: '002'
      SCRUTINY_WEB_INFLUXDB_PORT: '8086'
      COLLECTOR_API_ENDPOINT: http://127.0.0.1:8080
      PATH: /opt/scrutiny/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      INFLUXD_CONFIG_PATH: /opt/scrutiny/influxdb
      S6VER: 3.1.6.2
      INFLUXVER: 2.2.0
      S6_SERVICES_READYTIME: '1000'
    ports:
    - 31054:8080/tcp
    - 31055:8086/tcp
    networks:
    - ix-scrutiny_default
    healthcheck:
      test:
      - CMD
      - curl
      - --request
      - GET
      - --silent
      - --output
      - /dev/null
      - --show-error
      - --fail
      - http://127.0.0.1:8080/api/health
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  ix-scrutiny_default:
    external: true
