version: "3.9"

x-logging: &gelf_logging
  driver: gelf
  options:
    gelf-address: "udp://${GELF_HOST}:${GELF_PORT}"
    tag: "{{.Name}}"
    
services:
  db:
    image: postgis/postgis:${PG_TAG:-16-3.5}
    container_name: adventurelog_db
    restart: unless-stopped
    logging: *gelf_logging
    environment:
      POSTGRES_DB: changeme
      POSTGRES_USER: changeme
      POSTGRES_PASSWORD: changeme
    volumes:
      - ${STORAGE_ROOT}/postgres:/var/lib/postgresql/data

  backend:
    image: ghcr.io/seanmorley15/adventurelog-backend:${BACKEND_TAG:-latest}
    container_name: adventurelog_backend
    restart: unless-stopped
    logging: *gelf_logging
    depends_on:
      - db
    environment:
      PGHOST: changeme
      POSTGRES_DB: changeme
      POSTGRES_USER: changeme
      POSTGRES_PASSWORD: changeme
      SECRET_KEY: your-api-key-here
      DJANGO_ADMIN_USERNAME: changeme
      DJANGO_ADMIN_PASSWORD: changeme
      DJANGO_ADMIN_EMAIL: changeme
      PUBLIC_URL: changeme
      CSRF_TRUSTED_ORIGINS: changeme
      FRONTEND_URL: changeme
      DEBUG: changeme
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    volumes:
      - ${STORAGE_ROOT}/media:/code/media

  frontend:
    image: ghcr.io/seanmorley15/adventurelog-frontend:${FRONTEND_TAG:-latest}
    container_name: adventurelog_frontend
    restart: unless-stopped
    logging: *gelf_logging
    depends_on:
      - backend
    environment:
      PUBLIC_SERVER_URL: changeme
      VITE_API_URL: changeme
      ORIGIN: changeme
      BODY_SIZE_LIMIT: changeme
      FRONTEND_PORT: changeme
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}" 