version: '3.9'
services:
  ix-arcane-arcane-1:
    image: ghcr.io/getarcaneapp/arcane:v1.17.3
    container_name: ix-arcane-arcane-1
    restart: unless-stopped
    environment:
      UMASK: '002'
      GROUP_ID: '568'
      PUID: '568'
      NVIDIA_VISIBLE_DEVICES: void
      GID: '568'
      JWT_SECRET: ${JWT_SECRET}
      TZ: America/Los_Angeles
      PORT: '30258'
      UID: '568'
      PGID: '568'
      USER_ID: '568'
      UMASK_SET: '002'
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      GIN_MODE: release
      ENVIRONMENT: production
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      ROCR_VISIBLE_DEVICES: all
      HIP_VISIBLE_DEVICES: all
      ONEAPI_DEVICE_SELECTOR: level_zero:*,opencl:*
      LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/rocm/lib:/opt/intel/oneapi/lib:/opt/intel/oneapi/lib/intel64:/usr/lib/x86_64-linux-gnu:/usr/lib/aarch64-linux-gnu:/usr/lib64:/usr/lib:/lib64:/lib
    ports:
    - 30258:30258/tcp
    networks: ix-arcane_default
    healthcheck:
      test:
      - CMD
      - curl
      - --request
      - GET
      - --silent
      - --output
      - /dev/null
      - --show-error
      - --fail
      - http://127.0.0.1:30258/api/health
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  ix-arcane_default:
    external: true
