version: "3.8"

x-logging: &gelf_logging
  driver: gelf
  options:
    gelf-address: "udp://${GELF_HOST}:${GELF_PORT}"
    tag: "{{.Name}}"
    
services:
  wireguard-us-server:
    image: lscr.io/linuxserver/wireguard:${WG_TAG:-latest}
    container_name: wireguard-us-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
    environment:
      - PUID=${PUID}{PUID}
      - PGID=${PGID}{PGID}
      - TZ=${TZ}{TZ}
      - SERVERMODE=${SERVER_MODE}
    volumes:
      - ${STORAGE_ROOT}:/config
      - ${MODULES_PATH}:/lib/modules:ro
    ports:
      - "${SSH_PORT}:${SSH_PORT}/tcp"
      - "${HTTPS_PORT}:${HTTPS_PORT}/tcp"
    restart: unless-stopped
    logging: *gelf_logging