version: "3.9"

networks:
  books_net:

services:

  bookshelf:
    image: ghcr.io/pennydreadful/bookshelf:hardcover
    container_name: bookshelf
    restart: unless-stopped

    ports:
      - "8787:8787"

    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000

    dns:
      - 1.1.1.1
      - 8.8.8.8

    volumes:
      # Config
      - /path/to/mount/config

      # Downloads (normalized)
      - /path/to/mount/downloads/torrents
      - /path/to/mount/downloads/usenet

      # Final libraries
      - /path/to/mount/ebooks
      - /path/to/mount/audiobooks

    security_opt:
      - no-new-privileges:true
  # ---------------- Calibre ----------------
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    networks:
      - books_net
    ports:
      - 8099:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /path/to/mount/config
      - /path/to/mount/books/ebooks
      - /path/to/mount/inbox
    restart: unless-stopped

  # ---------------- Calibre-Web ----------------
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    networks:
      - books_net
    ports:
      - 8101:8083
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /path/to/mount/config
      - /path/to/mount/books
    restart: unless-stopped

  # ---------------- Audiobookshelf ----------------
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    networks:
      - books_net
    ports:
      - 13378:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /path/to/mount/config
      - /path/to/mount/metadata
      - /path/to/mount/audiobooks
    restart: unless-stopped

  calibre-importer:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre-importer
    networks:
      - books_net
    depends_on:
      - calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /path/to/mount/books
      - /path/to/mount/incoming
      - /path/to/mount/scripts
      - /path/to/mount/config
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y inotify-tools &&
      bash /scripts/import.sh
      "
    restart: unless-stopped