version: "3.9"

services:

  postgres:
    image: ossapps/postgres:17.7-trixie
    container_name: splitpro-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}{POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - /mnt/storagepool/apps_config/split-pro/postgres17:/var/lib/postgresql/data

    command: postgres -c shared_preload_libraries=pg_cron -c cron.database_name=splitpro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10


  splitpro:
    image: ossapps/splitpro:latest
    container_name: splitpro
    restart: unless-stopped

    depends_on:
      - postgres

    ports:
      - "3020:3000"

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      NEXTAUTH_SECRET=${AUTH_SECRET}{NEXTAUTH_SECRET}{NEXTAUTH_SECRET}        # was AUTH_SECRET
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
      AUTH_EMAIL_ENABLED: ${AUTH_EMAIL_ENABLED}
      FROM_EMAIL: ${FROM_EMAIL}
      EMAIL_SERVER_HOST: ${EMAIL_SERVER_HOST}    # was SMTP_HOST
      EMAIL_SERVER_PORT: ${EMAIL_SERVER_PORT}    # was SMTP_PORT
      EMAIL_SERVER_USER: ${EMAIL_SERVER_USER}    # was SMTP_USER
      EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}{EMAIL_SERVER_PASSWORD}  # was SMTP_PASSWORD
      DISABLE_EMAIL_SIGNUP: ${DISABLE_EMAIL_SIGNUP}
      ENABLE_SENDING_INVITES: ${ENABLE_SENDING_INVITES}   # this should be the default

    volumes:
      - /mnt/storagepool/apps_config/split-pro/uploads:/app/uploads