version: "3.9"

services:
  postgres:
    image: ossapps/postgres:${PG_TAG:-17.7-trixie}
    container_name: splitpro-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: changeme
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: changeme
    volumes:
      - ${STORAGE_ROOT}/postgres17:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_cron -c cron.database_name=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  splitpro:
    image: ossapps/splitpro:${SPLITPRO_TAG:-latest}
    container_name: splitpro
    restart: unless-stopped
    depends_on: [postgres]
    ports:
      - "${HOST_PORT}:3000"
    environment:
      DATABASE_URL: changeme
      NEXTAUTH_SECRET: changeme-secret
      NEXTAUTH_URL: changeme
      NEXTAUTH_URL_INTERNAL: changeme
      AUTH_EMAIL_ENABLED: changeme
      FROM_EMAIL: changeme
      EMAIL_SERVER_HOST: changeme
      EMAIL_SERVER_PORT: changeme
      EMAIL_SERVER_USER: changeme
      EMAIL_SERVER_PASSWORD: changeme
      DISABLE_EMAIL_SIGNUP: changeme
      ENABLE_SENDING_INVITES: changeme
    volumes:
      - ${STORAGE_ROOT}/uploads:/app/uploads