version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped

    ports:
      - "6333:6333"
      - "6334:6334"

    environment:
      - QDRANT__STORAGE__WAL_CAPACITY_MB=64
      - QDRANT__STORAGE__WAL_SEGMENTS_AHEAD=2
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

    volumes:
      - /mnt/nvmepool/appsconfig/qdrant/storage:/qdrant/storage
      - /mnt/storagepool/apps_config/qdrant/snapshots:/qdrant/snapshots
      - /mnt/storagepool/apps_config/qdrant/config:/qdrant/config

    labels:
      - autoheal=true
