version: '3.9'
services:
  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    restart: unless-stopped
    environment:
      POSTGRES_DB: jellystat
      JWT_SECRET: ${JWT_SECRET}
      TZ: America/Los_Angeles
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: '5432'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      NODE_VERSION: 22.21.1
      YARN_VERSION: 1.22.22
    ports:
    - 8090:3000/tcp
    networks: jellystat-stack_default
    volumes:
    - ${DATA_PATH}:/app/backend/backup-data:rw
    healthcheck:
      test:
      - CMD
      - /usr/bin/wget
      - --no-verbose
      - --tries=1
      - --spider
      - http://localhost:3000/auth/isconfigured
      interval: 30000000000
      timeout: 5000000000
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  jellystat-db:
    image: postgres:17
    container_name: jellystat-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Los_Angeles
      POSTGRES_DB: jellystat
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/17/bin
      GOSU_VERSION: '1.19'
      LANG: en_US.utf8
      PG_MAJOR: '17'
      PG_VERSION: 17.8-1.pgdg13+1
      PGDATA: /var/lib/postgresql/data
    networks: jellystat-stack_default
    volumes:
    - ${DATA_PATH}:/var/lib/postgresql/data:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  jellystat-stack_default:
    external: true
