version: '3.3'
services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    ports:
      - '8084:8080'
    restart: unless-stopped
    volumes:
      - /path/to/data/apps_config/stirlingpdf/tesseract_data:/usr/share/tessdata
      - /path/to/data/apps_config/stirlingpdf/config:/configs
      - /path/to/data/apps_config/stirlingpdf/files_storage:/output
      - /path/to/data/apps_config/stirlingpdf/logs:/logs
      - /path/to/data/apps_config/stirlingpdf/pipeline:/pipeline
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=${LANGS}
      - SERVER_PORT=8080
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - PASSWORD_PROTECT=changeme
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - SECURITY_ENABLELOGIN=true