version: '3.3'
services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    ports:
      - '8084:8080'
    restart: unless-stopped
    volumes:
      - /path/to/your/data:/usr/share/tessdata
      - /path/to/your/data:/configs
      - /path/to/your/data:/output
      - /path/to/your/data:/logs
      - /path/to/your/data:/pipeline
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
      - SERVER_PORT=8080
      - ALLOWED_HOSTS=pdf.gsynch.com,100.119.204.23,your-server-ip
      - PASSWORD_PROTECT=true
      - USERNAME=${USERNAME}
      - PASSWORD=${PDF_ADMIN_PASSWORD}
      - SECURITY_ENABLELOGIN=true