version: "3.9"

services:
  homebox:
    image: ghcr.io/greenalderman/homebox:latest
    container_name: homebox
    ports:
      - "3030:3030"
    environment:
      - GBOX_CONFIG_FILE=/data/homebox.conf
      - TZ=America/Los_Angeles
    volumes:
      - /path/to/homebox/data:/data
      - /path/to/homebox/data:/data
    restart: unless-stopped
