services:
  app:
    image: ghcr.io/javedh-dev/tracktor:${TR_TAG:-latest}
    container_name: tracktor-app
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - ${STORAGE_ROOT}:/data
    environment:
      - TRACKTOR_DEMO_MODE=changeme
      - FORCE_DATA_SEED=changeme
      - CORS_ORIGINS=changeme