version: "3.8"
    
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - COLLECTIONS=crowdsecurity/linux crowdsecurity/http-cve
    volumes:
      - /path/to/your/data:/etc/crowdsec/acquis.yaml
      - /path/to/your/data:/var/lib/crowdsec/data
      - /var/log:/var/log:ro
      - /path/to/your/data:/var/log/nginx:ro
    ports:
      - "6060:6060"   # Prometheus metrics
      - "1514:1514/udp"          # Syslog ingest from Graylog (UDP)

    networks:
      - crowdsec-net


  crowdsec-cloudflare-bouncer:
    image: crowdsecurity/cloudflare-bouncer:latest
    container_name: crowdsec-cloudflare-bouncer
    restart: unless-stopped
    volumes:
      - /path/to/your/data:/etc/crowdsec/bouncers/crowdsec-cloudflare-bouncer.yaml:ro
    depends_on:
      - crowdsec
    networks:
      - crowdsec-net

networks:
  crowdsec-net:
    driver: bridge