version: '3.9'
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      BASE_URL: http://${HOST_IP}:30159
      PLAYWRIGHT_DRIVER_URL: ws://browser-sockpuppet-chrome:3000
      FETCH_WORKERS: '5'
      MINIMUM_SECONDS_RECHECK_TIME: '60'
      HIDE_REFERER: 'true'
      PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LANG: C.UTF-8
      GPG_KEY: ${GPG_KEY}
      PYTHON_VERSION: 3.11.15
      PYTHON_SHA256: 272179ddd9a2e41a0fc8e42e33dfbdca0b3711aa5abf372d3f2d51543d09b625
      PYTHONUNBUFFERED: '1'
      PYTHONPATH: /usr/local
      LOGGER_LEVEL: ''
      LC_ALL: en_US.UTF-8
    ports:
    - 30159:5000/tcp
    networks: changedetection-stack_changedetection_net
    volumes:
    - ${DATA_PATH}:/datastore:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  changedetection-browser:
    image: dgtlmoon/sockpuppetbrowser:latest
    container_name: changedetection-browser
    restart: unless-stopped
    environment:
      SCREEN_WIDTH: '1920'
      SCREEN_HEIGHT: '1080'
      SCREEN_DEPTH: '16'
      MAX_CONCURRENT_CHROME_PROCESSES: '10'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      CHROME_BIN: /usr/bin/chromium-browser
      CHROME_PATH: /usr/lib/chromium/
      CHROMIUM_FLAGS: --disable-software-rasterizer --disable-dev-shm-usage
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
      PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH: /usr/bin/chromium-browser
      PYTHONUNBUFFERED: '1'
      LOG_LEVEL: DEBUG
    networks: changedetection-stack_changedetection_net
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  changedetection-stack_changedetection_net:
    external: true
