services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    hostname: changedetection
    user: "3001:3000"
    restart: unless-stopped

    depends_on:
      browser-sockpuppet-chrome:
        condition: service_started

    ports:
      - "30159:5000"

    environment:
      - TZ=${TZ}
      - BASE_URL=${BASE_URL}
      - PLAYWRIGHT_DRIVER_URL=${PLAYWRIGHT_DRIVER_URL}
      - FETCH_WORKERS=5
      - MINIMUM_SECONDS_RECHECK_TIME=60
      - HIDE_REFERER=true

    volumes:
      - /path/to/data/apps_config/changedetection/datastore:/datastore

    networks:
      - changedetection_net

    security_opt:
      - no-new-privileges:true

    tmpfs:
      - /tmp:size=256m,mode=1777


  browser-sockpuppet-chrome:
    image: dgtlmoon/sockpuppetbrowser:latest
    container_name: changedetection-browser
    hostname: browser-sockpuppet-chrome
    restart: unless-stopped

    shm_size: "2gb"

    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10

    networks:
      - changedetection_net

    security_opt:
      - no-new-privileges:true

    cap_add:
      - SYS_ADMIN


networks:
  changedetection_net:
    driver: bridge