version: '3.9'
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      N8N_PROTOCOL: https
      N8N_TRUST_PROXY: 'true'
      N8N_API_KEY: ${N8N_API_KEY}
      N8N_HOST: ${N8N_DOMAIN}
      N8N_SECURE_COOKIE: 'false'
      DB_POSTGRESDB_HOST: n8n-postgres
      TZ: America/Los_Angeles
      DB_POSTGRESDB_PASSWORD: ${DB_POSTGRESDB_PASSWORD}
      DB_TYPE: postgresdb
      DB_POSTGRESDB_PORT: '5432'
      DB_POSTGRESDB_DATABASE: n8n
      WEBHOOK_URL: https://${N8N_DOMAIN}
      N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES: 'false'
      N8N_PORT: '5678'
      GENERIC_TIMEZONE: America/Los_Angeles
      DB_POSTGRESDB_USER: n8n
      N8N_ALLOW_FILE_ACCESS: /data
      N8N_ENABLE_COMMUNITY_NODES: 'true'
      N8N_AI_ENABLED: 'true'
      NODE_VERSION: 24.13.1
      NPM_CONFIG_UPDATE_NOTIFIER: 'false'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      NODE_PATH: /opt/nodejs/node-v24.13.1/lib/node_modules
      NODE_ENV: production
      N8N_RELEASE_TYPE: stable
      SHELL: /bin/sh
    ports:
    - 5678:5678/tcp
    networks:
    - n8n-portainer-stack_default
    - trading-net-ron
    volumes:
    - ${DATA_PATH}:/home/node/.n8n:rw
    - ${DATA_PATH}:/home/node/.n8n-files:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  n8n-postgres:
    image: postgres:15-alpine
    container_name: n8n-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      GOSU_VERSION: '1.19'
      LANG: en_US.utf8
      PG_MAJOR: '15'
      PG_VERSION: '15.17'
      PG_SHA256: ae14f24c14727e0b2ded1c5553031666099bd1054db3ef44bfa6e2bd6d554a56
      DOCKER_PG_LLVM_DEPS: "llvm19-dev \t\tclang19"
      PGDATA: /var/lib/postgresql/data
    networks: n8n-portainer-stack_default
    volumes:
    - ${DATA_PATH}:/var/lib/postgresql/data:rw
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U n8n -d n8n
      interval: 10000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  n8n-portainer-stack_default:
    external: true
  trading-net-ron:
    external: true
