version: '3.9'
services:
  ix-nextcloud-cron-1:
    image: ix-nextcloud:33.0.2_2d91b2869075cb02556af5819ab2fc278f4bcf751f535ea675c8104091781dba
    container_name: ix-nextcloud-cron-1
    restart: unless-stopped
    environment:
      OVERWRITEHOST: ${NEXTCLOUD_DOMAIN}
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
      TRUSTED_PROXIES: 127.0.0.1 ${HOST_IP}/16 ${LAN_IP_172}/12 ${LAN_IP_10}/8
      NVIDIA_VISIBLE_DEVICES: void
      OVERWRITEPROTOCOL: https
      PHP_UPLOAD_LIMIT: 3G
      REDIS_HOST: redis
      POSTGRES_HOST: postgres:5432
      UMASK_SET: '002'
      REDIS_HOST_PORT: '6379'
      NEXTCLOUD_ADMIN_USER: gaurav
      REDIS_HOST_PASSWORD: ${REDIS_HOST_PASSWORD}
      NEXTCLOUD_DATA_DIR: /var/www/html/data
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APACHE_DISABLE_REWRITE_IP: '1'
      OVERWRITECLIURL: ${NEXTCLOUD_DOMAIN}
      UMASK: '002'
      TZ: America/Los_Angeles
      PHP_MEMORY_LIMIT: 512M
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: 127.0.0.1 localhost nextcloud nginx
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PHPIZE_DEPS: "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\
        \tmake \t\tpkg-config \t\tre2c"
      PHP_INI_DIR: /usr/local/etc/php
      APACHE_CONFDIR: /etc/apache2
      APACHE_ENVVARS: /etc/apache2/envvars
      PHP_CFLAGS: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
      PHP_CPPFLAGS: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
      PHP_LDFLAGS: -Wl,-O1 -pie
      GPG_KEYS: ${GPG_KEYS}
      PHP_VERSION: 8.4.20
      PHP_URL: https://www.php.net/distributions/php-8.4.20.tar.xz
      PHP_ASC_URL: https://www.php.net/distributions/php-8.4.20.tar.xz.asc
      PHP_SHA256: e454c6f7c89a42f41ebb06dc5c3578e8c8b5f1a3f0da6675665affab04e221f7
      PHP_OPCACHE_MEMORY_CONSUMPTION: '128'
      APACHE_BODY_LIMIT: '1073741824'
      NEXTCLOUD_VERSION: 33.0.2
    networks: ix-nextcloud_ix-internal-nextcloud-net
    healthcheck:
      test:
      - CMD
      - pidof
      - -s
      - busybox
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  ix-nextcloud-nginx-1:
    image: nginx:1.29.8
    container_name: ix-nextcloud-nginx-1
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      UMASK: '002'
      UMASK_SET: '002'
      NVIDIA_VISIBLE_DEVICES: void
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      NGINX_VERSION: 1.29.8
      NJS_VERSION: 0.9.6
      NJS_RELEASE: 1~trixie
      ACME_VERSION: 0.3.1
      PKG_RELEASE: 1~trixie
      DYNPKG_RELEASE: 1~trixie
    ports:
    - 30027:30027/tcp
    networks: ix-nextcloud_ix-internal-nextcloud-net
    healthcheck:
      test:
      - CMD
      - curl
      - --request
      - GET
      - --silent
      - --output
      - /dev/null
      - --show-error
      - --fail
      - --insecure
      - --header
      - 'Host: localhost'
      - https://127.0.0.1:30027/status.php
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  ix-nextcloud-nextcloud-1:
    image: ix-nextcloud:33.0.2_2d91b2869075cb02556af5819ab2fc278f4bcf751f535ea675c8104091781dba
    container_name: ix-nextcloud-nextcloud-1
    restart: unless-stopped
    environment:
      OVERWRITEHOST: ${NEXTCLOUD_DOMAIN}
      APACHE_DISABLE_REWRITE_IP: '1'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      OVERWRITEPROTOCOL: https
      NEXTCLOUD_DATA_DIR: /var/www/html/data
      NEXTCLOUD_ADMIN_USER: gaurav
      POSTGRES_USER: nextcloud
      REDIS_HOST_PASSWORD: ${REDIS_HOST_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: 127.0.0.1 localhost nextcloud nginx
      PHP_MEMORY_LIMIT: 512M
      REDIS_HOST: redis
      TRUSTED_PROXIES: 127.0.0.1 ${HOST_IP}/16 ${LAN_IP_172}/12 ${LAN_IP_10}/8
      UMASK_SET: '002'
      OVERWRITECLIURL: ${NEXTCLOUD_DOMAIN}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      POSTGRES_HOST: postgres:5432
      REDIS_HOST_PORT: '6379'
      TZ: America/Los_Angeles
      UMASK: '002'
      NVIDIA_VISIBLE_DEVICES: void
      POSTGRES_DB: nextcloud
      PHP_UPLOAD_LIMIT: 3G
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PHPIZE_DEPS: "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\
        \tmake \t\tpkg-config \t\tre2c"
      PHP_INI_DIR: /usr/local/etc/php
      APACHE_CONFDIR: /etc/apache2
      APACHE_ENVVARS: /etc/apache2/envvars
      PHP_CFLAGS: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
      PHP_CPPFLAGS: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
      PHP_LDFLAGS: -Wl,-O1 -pie
      GPG_KEYS: ${GPG_KEYS}
      PHP_VERSION: 8.4.20
      PHP_URL: https://www.php.net/distributions/php-8.4.20.tar.xz
      PHP_ASC_URL: https://www.php.net/distributions/php-8.4.20.tar.xz.asc
      PHP_SHA256: e454c6f7c89a42f41ebb06dc5c3578e8c8b5f1a3f0da6675665affab04e221f7
      PHP_OPCACHE_MEMORY_CONSUMPTION: '128'
      APACHE_BODY_LIMIT: '1073741824'
      NEXTCLOUD_VERSION: 33.0.2
    networks: ix-nextcloud_ix-internal-nextcloud-net
    healthcheck:
      test:
      - CMD
      - curl
      - --request
      - GET
      - --silent
      - --output
      - /dev/null
      - --show-error
      - --fail
      - --header
      - 'Host: localhost'
      - http://127.0.0.1:80/status.php
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  ix-nextcloud-postgres-1:
    image: postgres:17.9-bookworm
    container_name: ix-nextcloud-postgres-1
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextcloud
      UMASK: '002'
      TZ: America/Los_Angeles
      PGDATA: /var/lib/postgresql/17/docker
      POSTGRES_USER: nextcloud
      UMASK_SET: '002'
      PGPORT: '5432'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NVIDIA_VISIBLE_DEVICES: void
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/17/bin
      GOSU_VERSION: '1.19'
      LANG: en_US.utf8
      PG_MAJOR: '17'
      PG_VERSION: 17.9-1.pgdg12+1
    networks: ix-nextcloud_ix-internal-nextcloud-net
    healthcheck:
      test:
      - CMD
      - pg_isready
      - -h
      - 127.0.0.1
      - -p
      - '5432'
      - -U
      - nextcloud
      - -d
      - nextcloud
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  ix-nextcloud-redis-1:
    image: valkey/valkey:9.0.3
    container_name: ix-nextcloud-redis-1
    restart: unless-stopped
    environment:
      NVIDIA_VISIBLE_DEVICES: void
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TZ: America/Los_Angeles
      UMASK: '002'
      UMASK_SET: '002'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      VALKEY_VERSION: ${VALKEY_VERSION}
    networks: ix-nextcloud_ix-internal-nextcloud-net
    healthcheck:
      test:
      - CMD
      - redis-cli
      - -h
      - 127.0.0.1
      - -p
      - '6379'
      - -a
      - Whiteknight007!
      - ping
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  ix-nextcloud-imaginary-1:
    image: ghcr.io/nextcloud-releases/aio-imaginary:20260409_094910
    container_name: ix-nextcloud-imaginary-1
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      UMASK: '002'
      UMASK_SET: '002'
      NVIDIA_VISIBLE_DEVICES: void
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PORT: '9000'
      MALLOC_ARENA_MAX: '2'
    networks: ix-nextcloud_ix-internal-nextcloud-net
    healthcheck:
      test:
      - CMD
      - wget
      - --quiet
      - --spider
      - http://127.0.0.1:9000/health
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  ix-nextcloud_ix-internal-nextcloud-net:
    external: true
