version: "3.8"

services:
  bichon:
    image: rustmailer/bichon:${BICHON_TAG:-latest}
    container_name: bichon
    restart: unless-stopped
    environment:
      - BICHON_LOG_LEVEL=changeme
      - BICHON_ROOT_DIR=/data
      - BICHON_ENABLE_ACCESS_TOKEN=your-api-key-here
      - BICHON_CORS_ORIGINS=changeme
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - ${STORAGE_ROOT}:/data:rw
    security_opt:
      - no-new-privileges:true