version: '3.9'
services:
  bichon:
    image: rustmailer/bichon:latest
    container_name: bichon
    restart: unless-stopped
    environment:
      BICHON_LOG_LEVEL: info
      BICHON_ROOT_DIR: /data
      BICHON_ENABLE_ACCESS_TOKEN: 'true'
      BICHON_CORS_ORIGINS: http://localhost:15630,http://${HOST_IP}:15630,${MAIL_DOMAIN}
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
    - 15630:15630/tcp
    networks: bichon-stack_default
    volumes:
    - ${DATA_PATH}:/data:rw
    healthcheck:
      test:
      - CMD-SHELL
      - curl -fs http://localhost:15630/api/status || exit 1
      interval: 30000000000
      timeout: 5000000000
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  bichon-stack_default:
    external: true
