version: "3.9"

services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:v0.8.6-omnibus
    container_name: scrutiny
    ports:
      - "8086:8080"
      - "8087:8086"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /path/to/scrutiny/config:/opt/scrutiny/config
      - /path/to/scrutiny/influxdb:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro
    restart: unless-stopped
