version: '3.9'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      PUID: '3001'
      PGID: '3000'
      TZ: America/Los_Angeles
      PATH: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PS1: '$(whoami)@$(hostname):$(pwd)\$ '
      HOME: /root
      TERM: xterm
      S6_CMD_WAIT_FOR_SERVICES_MAXTIME: '0'
      S6_VERBOSITY: '1'
      S6_STAGE2_HOOK: /docker-mods
      VIRTUAL_ENV: /lsiopy
      LSIO_FIRST_PARTY: 'true'
      XDG_CONFIG_HOME: /config/xdg
      SONARR_CHANNEL: v4-stable
      SONARR_BRANCH: main
      COMPlus_EnableDiagnostics: '0'
      TMPDIR: /run/sonarr-temp
    ports:
    - 8989:8989/tcp
    networks: arrnet
    volumes:
    - ${DATA_PATH}:/config:rw
    - ${DATA_PATH}:/downloadsq:rw
    - ${DATA_PATH}:/downloads:rw
    - ${DATA_PATH}:/tv:rw
    logging:
      driver: gelf
      options:
        gelf-address: udp://${HOST_IP}:12201
        tag: '{{.Name}}'
networks:
  arrnet:
    external: true
