name: immichframe
services:
  immichframe:
    container_name: immichframe
    image: ghcr.io/immichframe/immichframe:${IMF_TAG:-latest}
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    environment:
      TZ: ${TZ}
      ImmichServerUrl: changeme
      ApiKey: your-api-key-here
      AuthenticationSecret: changeme-secret
      Interval: changeme
      TransitionDuration: changeme
      ImageZoom: changeme
      ImageFill: changeme
      Layout: changeme
      DownloadImages: changeme
      RenewImagesDuration: changeme
      Albums: changeme
      PLAYBACK_MODE: changeme
      ShowClock: changeme
      ClockFormat: changeme
      ShowPhotoDate: changeme
      PhotoDateFormat: changeme
      ShowPeopleDesc: changeme
      ShowImageLocation: changeme
      ImageLocationFormat: changeme
      ImagePan: changeme
      ShowVideos: changeme
      WeatherApiKey: your-api-key-here
      ShowWeatherDescription: changeme
      UnitSystem: changeme
      WeatherLatLong: changeme
      Language: changeme
    volumes:
      - ${CACHE_ROOT}:/app/ImageCache