name: immichframe
services:
  immichframe:
    container_name: immichframe
    image: ghcr.io/immichframe/immichframe:${IMF_TAG:-latest}
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    environment:
      TZ=${TZ}{TZ}
      ImmichServerUrl: ${IMMICH_URL}
      ApiKey: ${IMMICH_API_KEY}
      AuthenticationSecret: ${AUTH_SECRET}
      Interval: ${INTERVAL}
      TransitionDuration: ${TRANSITION_DURATION}
      ImageZoom: ${IMAGE_ZOOM}
      ImageFill: ${IMAGE_FILL}
      Layout: ${LAYOUT}
      DownloadImages: ${DOWNLOAD_IMAGES}
      RenewImagesDuration: ${RENEW_IMAGES_DURATION}
      Albums: ${ALBUMS}
      PLAYBACK_MODE: ${PLAYBACK_MODE}
      ShowClock: ${SHOW_CLOCK}
      ClockFormat: ${CLOCK_FORMAT}
      ShowPhotoDate: ${SHOW_PHOTO_DATE}
      PhotoDateFormat: ${PHOTO_DATE_FORMAT}
      ShowPeopleDesc: ${SHOW_PEOPLE_DESC}
      ShowImageLocation: ${SHOW_IMAGE_LOCATION}
      ImageLocationFormat: ${IMAGE_LOCATION_FORMAT}
      ImagePan: ${IMAGE_PAN}
      ShowVideos: ${SHOW_VIDEOS}
      WeatherApiKey: ${WEATHER_API_KEY}
      ShowWeatherDescription: ${SHOW_WEATHER_DESCRIPTION}
      UnitSystem: ${UNIT_SYSTEM}
      WeatherLatLong: ${WEATHER_LAT_LONG}
      Language: ${LANGUAGE}
    volumes:
      - ${CACHE_ROOT}:/app/ImageCache