version: '3.9'
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    restart: unless-stopped
    environment:
      PUID: '3001'
      PGID: '3000'
      TZ: America/Los_Angeles
      PATH: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      HOME: /config
      LANGUAGE: en_US.UTF-8
      LANG: en_US.UTF-8
      TERM: xterm
      S6_CMD_WAIT_FOR_SERVICES_MAXTIME: '0'
      S6_VERBOSITY: '1'
      S6_STAGE2_HOOK: /docker-mods
      VIRTUAL_ENV: /lsiopy
      DISPLAY: :1
      PERL5LIB: /usr/local/bin
      START_DOCKER: 'true'
      PULSE_RUNTIME_PATH: /defaults
      SELKIES_INTERPOSER: /usr/lib/selkies_joystick_interposer.so
      NVIDIA_DRIVER_CAPABILITIES: all
      DISABLE_ZINK: 'false'
      DISABLE_DRI3: 'false'
      TITLE: Calibre
      LSIO_FIRST_PARTY: 'true'
      CUSTOM_PORT: '8080'
      CUSTOM_HTTPS_PORT: '8181'
      QTWEBENGINE_DISABLE_SANDBOX: '1'
    ports:
    - 8099:8080/tcp
    networks: book-stack_books_net
    volumes:
    - ${DATA_PATH}:/config:rw
    - ${DATA_PATH}:/books/ebooks:rw
    - ${DATA_PATH}:/inbox:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  calibre-importer:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre-importer
    restart: unless-stopped
    environment:
      PUID: '3001'
      PGID: '3000'
      TZ: America/Los_Angeles
      PATH: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      HOME: /config
      LANGUAGE: en_US.UTF-8
      LANG: en_US.UTF-8
      TERM: xterm
      S6_CMD_WAIT_FOR_SERVICES_MAXTIME: '0'
      S6_VERBOSITY: '1'
      S6_STAGE2_HOOK: /docker-mods
      VIRTUAL_ENV: /lsiopy
      DISPLAY: :1
      PERL5LIB: /usr/local/bin
      START_DOCKER: 'true'
      PULSE_RUNTIME_PATH: /defaults
      SELKIES_INTERPOSER: /usr/lib/selkies_joystick_interposer.so
      NVIDIA_DRIVER_CAPABILITIES: all
      DISABLE_ZINK: 'false'
      DISABLE_DRI3: 'false'
      TITLE: Calibre
      LSIO_FIRST_PARTY: 'true'
      CUSTOM_PORT: '8080'
      CUSTOM_HTTPS_PORT: '8181'
      QTWEBENGINE_DISABLE_SANDBOX: '1'
    networks: book-stack_books_net
    volumes:
    - ${DATA_PATH}:/incoming:rw
    - ${DATA_PATH}:/scripts:rw
    - ${DATA_PATH}:/config:rw
    - ${DATA_PATH}:/books:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      PGID: '3000'
      TZ: America/Los_Angeles
      PUID: '3001'
      PATH: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      HOME: /root
      LANGUAGE: en_US.UTF-8
      LANG: en_US.UTF-8
      TERM: xterm
      S6_CMD_WAIT_FOR_SERVICES_MAXTIME: '0'
      S6_VERBOSITY: '1'
      S6_STAGE2_HOOK: /docker-mods
      VIRTUAL_ENV: /lsiopy
      LSIO_FIRST_PARTY: 'true'
      QTWEBENGINE_CHROMIUM_FLAGS: --no-sandbox
    ports:
    - 8101:8083/tcp
    networks: book-stack_books_net
    volumes:
    - ${DATA_PATH}:/config:rw
    - ${DATA_PATH}:/books:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  book-stack_books_net:
    external: true
