version: "3.8"
services:
  npmplus:
    image: zoeyvid/npmplus:2026-04-12-r1
    container_name: npmplus
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DISABLE_HTTP=true
      - CROWDSEC_LAPI_URL=http://crowdsec:8080
      - CROWDSEC_LAPI_KEY=${API_KEY}
    ports:
      - "443:443/tcp"
      - "443:443/udp" 
      - "8181:81/tcp" 
    volumes:
      - /mnt/storagepool/apps_config/npmplus/data:/data
    networks:
      - default
      - crowdsec_net
    healthcheck:
      disable: true

networks:
  default:
  crowdsec_net:
    external: true
    name: crowdsec-stack_crowdsec-net