version: '3.9'
services:
  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuparr
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      PUID: '3001'
      PGID: '3000'
      PATH: /opt/apprise-venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      APP_UID: '1654'
      ASPNETCORE_HTTP_PORTS: '8080'
      DOTNET_RUNNING_IN_CONTAINER: 'true'
      DOTNET_VERSION: 10.0.5
      ASPNET_VERSION: 10.0.5
      VIRTUAL_ENV: /opt/apprise-venv
      UMASK: '022'
      HTTP_PORTS: '11011'
      DOTNET_USE_POLLING_FILE_WATCHER: 'true'
    ports:
    - 11011:11011/tcp
    networks: arrnet
    volumes:
    - ${DATA_PATH}:/config:rw
    - ${DATA_PATH}:/downloadsq:rw
    logging:
      driver: gelf
      options:
        gelf-address: udp://${HOST_IP}:12201
        tag: '{{.Name}}'
networks:
  arrnet:
    external: true
