version: "3.8"

services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger:${LL_TAG:-latest}
    container_name: lubelogger
    restart: unless-stopped
    environment:
      PUID: changeme
      PGID: changeme
      TZ: ${TZ}
      ASPNETCORE_URLS: changeme
      LL__Locale: changeme
      LL__Culture: changeme
      LL__Smtp__Enabled: "changeme"
      LL__MOTD__Enabled: "changeme"
      ASPNETCORE_DATAPROTECTION__DIRECTORY: /App/keys
    volumes:
      - ${STORAGE_ROOT}/data:/App/data
      - ${STORAGE_ROOT}/keys:/App/keys
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}" 