version: '3.9'
services:
  learning_1:
    image: ghcr.io/immich-app/immich-machine-learning:v2.7.3-cuda
    container_name: ix-immich-machine-learning-1
    restart: unless-stopped
    environment:
      PGID: '568'
      UID: '568'
      NVIDIA_VISIBLE_DEVICES: GPU-9ed0a08d-a22d-60e2-d4eb-ad4a6b8d5fa2
      PUID: '568'
      GID: '568'
      MPLCONFIGDIR: /mlcache/matplotlib
      NVIDIA_DRIVER_CAPABILITIES: all
      MACHINE_LEARNING_DEVICE: cuda
      TZ: America/Los_Angeles
      UMASK_SET: '002'
      UMASK: '002'
      NODE_ENV: production
      HF_HOME: /mlcache
      GROUP_ID: '568'
      TRANSFORMERS_CACHE: /mlcache
      MACHINE_LEARNING_CACHE_FOLDER: /mlcache
      IMMICH_LOG_LEVEL: log
      IMMICH_PORT: '32002'
      USER_ID: '568'
      PATH: /opt/venv/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      NVARCH: x86_64
      NVIDIA_REQUIRE_CUDA: cuda>=12.2 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471
        brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471
        brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471
        brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471
        brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=525,driver<526
        brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526
        brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526
        brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526
        brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526
      NV_CUDA_CUDART_VERSION: 12.2.140-1
      NV_CUDA_COMPAT_PACKAGE: cuda-compat-12-2
      CUDA_VERSION: 12.2.2
      LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
      NV_CUDA_LIB_VERSION: 12.2.2-1
      NV_NVTX_VERSION: 12.2.140-1
      NV_LIBNPP_VERSION: 12.2.1.4-1
      NV_LIBNPP_PACKAGE: libnpp-12-2=12.2.1.4-1
      NV_LIBCUSPARSE_VERSION: 12.1.2.141-1
      NV_LIBCUBLAS_PACKAGE_NAME: libcublas-12-2
      NV_LIBCUBLAS_VERSION: 12.2.5.6-1
      NV_LIBCUBLAS_PACKAGE: libcublas-12-2=12.2.5.6-1
      NV_LIBNCCL_PACKAGE_NAME: libnccl2
      NV_LIBNCCL_PACKAGE_VERSION: 2.19.3-1
      NCCL_VERSION: 2.19.3-1
      NV_LIBNCCL_PACKAGE: libnccl2=2.19.3-1+cuda12.2
      NVIDIA_PRODUCT_NAME: CUDA
      LD_PRELOAD: /usr/lib/libmimalloc.so.2
      MACHINE_LEARNING_MODEL_ARENA: 'false'
      PYTHONDONTWRITEBYTECODE: '1'
      PYTHONUNBUFFERED: '1'
      PYTHONPATH: /usr/src
      DEVICE: cuda
      VIRTUAL_ENV: /opt/venv
      IMMICH_BUILD: '24205962760'
      IMMICH_BUILD_URL: https://github.com/immich-app/immich/actions/runs/24205962760
      IMMICH_BUILD_IMAGE: v2.7.3
      IMMICH_BUILD_IMAGE_URL: https://github.com/immich-app/immich/pkgs/container/immich-machine-learning
      IMMICH_REPOSITORY: immich-app/immich
      IMMICH_REPOSITORY_URL: https://github.com/immich-app/immich
      IMMICH_SOURCE_REF: v2.7.3
      IMMICH_SOURCE_COMMIT: 3254d31cd2967ad878f9bc5fb8b25738c8fd883a
      IMMICH_SOURCE_URL: https://github.com/immich-app/immich/commit/3254d31cd2967ad878f9bc5fb8b25738c8fd883a
    networks:
    - ix-immich_ix-internal-immich-net
    healthcheck:
      test:
      - CMD
      - python3
      - healthcheck.py
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  immich_pgvecto_1:
    image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3
    container_name: ix-immich-pgvecto-1
    restart: unless-stopped
    environment:
      POSTGRES_USER: immich
      UMASK: '002'
      UMASK_SET: '002'
      POSTGRES_DB: immich
      PGPORT: '5432'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Los_Angeles
      GID: '568'
      PUID: '568'
      PGDATA: /var/lib/postgresql/18/docker
      NVIDIA_VISIBLE_DEVICES: GPU-9ed0a08d-a22d-60e2-d4eb-ad4a6b8d5fa2
      NVIDIA_DRIVER_CAPABILITIES: all
      UID: '568'
      GROUP_ID: '568'
      USER_ID: '568'
      DB_STORAGE_TYPE: HDD
      PGID: '568'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/18/bin
      GOSU_VERSION: '1.19'
      LANG: en_US.utf8
      PG_MAJOR: '18'
      PG_VERSION: 18.2-1.pgdg12+1
    networks:
    - ix-immich_ix-internal-immich-net
    healthcheck:
      test:
      - CMD
      - pg_isready
      - -h
      - 127.0.0.1
      - -p
      - '5432'
      - -U
      - immich
      - -d
      - immich
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  immich_redis_1:
    image: valkey/valkey:9.0.3
    container_name: ix-immich-redis-1
    restart: unless-stopped
    environment:
      UMASK: '002'
      USER_ID: '568'
      NVIDIA_VISIBLE_DEVICES: GPU-9ed0a08d-a22d-60e2-d4eb-ad4a6b8d5fa2
      NVIDIA_DRIVER_CAPABILITIES: all
      PUID: '568'
      GID: '568'
      PGID: '568'
      UID: '568'
      TZ: America/Los_Angeles
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      UMASK_SET: '002'
      GROUP_ID: '568'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      VALKEY_VERSION: ${VALKEY_VERSION}
    networks:
    - ix-immich_ix-internal-immich-net
    healthcheck:
      test:
      - CMD
      - redis-cli
      - -h
      - 127.0.0.1
      - -p
      - '6379'
      - -a
      - Whiteknight007!
      - ping
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  immich_server_1:
    image: ghcr.io/immich-app/immich-server:v2.7.3
    container_name: ix-immich-server-1
    restart: unless-stopped
    environment:
      REDIS_PORT: '6379'
      TZ: America/Los_Angeles
      DB_HOSTNAME: pgvecto
      GID: '568'
      IMMICH_MACHINE_LEARNING_ENABLED: 'true'
      DB_DATABASE_NAME: immich
      NVIDIA_VISIBLE_DEVICES: GPU-9ed0a08d-a22d-60e2-d4eb-ad4a6b8d5fa2
      NVIDIA_DRIVER_CAPABILITIES: all
      PUID: '568'
      IMMICH_MICROSERVICES_METRICS_PORT: '30364'
      DB_USERNAME: immich
      GROUP_ID: '568'
      UID: '568'
      UMASK_SET: '002'
      NODE_ENV: production
      USER_ID: '568'
      IMMICH_MACHINE_LEARNING_URL: http://machine-learning:32002
      DB_PORT: '5432'
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      IMMICH_PORT: '30041'
      MACHINE_LEARNING_DEVICE: cuda
      REDIS_HOSTNAME: redis
      UMASK: '002'
      IMMICH_API_METRICS_PORT: '30363'
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_DBINDEX: '0'
      PGID: '568'
      IMMICH_LOG_LEVEL: log
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/src/app/server/bin
      NODE_VERSION: 24.14.1
      YARN_VERSION: 1.22.22
      DEBIAN_RELEASE: trixie
      LD_LIBRARY_PATH: /usr/lib/jellyfin-ffmpeg/lib:/usr/lib/wsl/lib
      IMMICH_BUILD: '24205962760'
      IMMICH_BUILD_URL: https://github.com/immich-app/immich/actions/runs/24205962760
      IMMICH_BUILD_IMAGE: v2.7.3
      IMMICH_BUILD_IMAGE_URL: https://github.com/immich-app/immich/pkgs/container/immich-server
      IMMICH_REPOSITORY: immich-app/immich
      IMMICH_REPOSITORY_URL: https://github.com/immich-app/immich
      IMMICH_SOURCE_REF: v2.7.3
      IMMICH_SOURCE_COMMIT: 3254d31cd2967ad878f9bc5fb8b25738c8fd883a
      IMMICH_SOURCE_URL: https://github.com/immich-app/immich/commit/3254d31cd2967ad878f9bc5fb8b25738c8fd883a
    ports:
    - 30041:30041/tcp
    networks:
    - ix-immich_ix-internal-immich-net
    healthcheck:
      test:
      - CMD
      - immich-healthcheck
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  ix-immich_ix-internal-immich-net:
    external: true
