version: '3.9'
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      PUID: '3001'
      PGID: '3000'
      PATH: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PS1: '$(whoami)@$(hostname):$(pwd)\$ '
      HOME: /config
      TERM: xterm
      S6_CMD_WAIT_FOR_SERVICES_MAXTIME: '0'
      S6_VERBOSITY: '1'
      S6_STAGE2_HOOK: /docker-mods
      VIRTUAL_ENV: /lsiopy
      LSIO_FIRST_PARTY: 'true'
      PYTHONIOENCODING: utf-8
    volumes:
    - ${DATA_PATH}:/config:rw
    - ${DATA_PATH}:/downloads:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks: {}
