version: '3.8'

services:
  react-app:
    image: node:16-alpine
    container_name: logistics-react
    working_dir: /app
    volumes:
      #- /mnt/storagepool/apps_config/Spartans/build:/app/build 
      - /mnt/storagepool/master/build:/app/build
    ports:
      - "3001:3001"
    command: sh -c "npm install -g serve && serve -s build -l 3001"
    restart: always