version: '3.9'
services:
  splitpro:
    image: ossapps/splitpro:latest
    container_name: splitpro
    restart: unless-stopped
    environment:
      DISABLE_EMAIL_SIGNUP: 'true'
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      AUTH_EMAIL_ENABLED: 'true'
      EMAIL_SERVER_USER: ${USER_EMAIL}
      NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
      EMAIL_SERVER_HOST: smtp.gmail.com
      FROM_EMAIL: ${USER_EMAIL}
      DATABASE_URL: postgresql://splitpro:3k2E7DrJq21y0B@postgres:5432/splitpro
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      EMAIL_SERVER_PORT: '587'
      EMAIL_SERVER_PASSWORD: ${EMAIL_SERVER_PASSWORD}
      ENABLE_SENDING_INVITES: 'true'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      NODE_VERSION: 22.16.0
      YARN_VERSION: 1.22.22
      NODE_ENV: production
      DOCKER_OUTPUT: '1'
      SKIP_ENV_VALIDATION: 'false'
      APP_VERSION: v2.0.1
    ports:
    - 3020:3000/tcp
    networks: split-pro-stack_default
    volumes:
    - ${DATA_PATH}:/app/uploads:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  splitpro-postgres:
    image: ossapps/postgres:17.7-trixie
    container_name: splitpro-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: splitpro
      POSTGRES_USER: splitpro
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/17/bin
      GOSU_VERSION: '1.19'
      LANG: en_US.utf8
      PG_MAJOR: '17'
      PG_VERSION: 17.7-3.pgdg13+1
      PGDATA: /var/lib/postgresql/data
    networks: split-pro-stack_default
    volumes:
    - ${DATA_PATH}:/var/lib/postgresql/data:rw
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U splitpro
      interval: 5000000000
      timeout: 5000000000
      retries: 10
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  split-pro-stack_default:
    external: true
