version: '3.9'
services:
  NodeExporter:
    image: prom/node-exporter:latest
    container_name: NodeExporter
    restart: always
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  host: {}
