version: '3.7'

services:
  onlyoffice-document-server:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-documentserver
    restart: always
    ports:
      - "8082:80"  # You can change 8082 to any available external port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/storagepool/apps_config/onlyoffice/data:/var/www/onlyoffice/Data
      - /mnt/storagepool/apps_config/onlyoffice/logs:/var/log/onlyoffice
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}