version: '3.9'
services:
  ix-flaresolverr-flaresolverr-1:
    image: flaresolverr/flaresolverr:v3.4.6
    container_name: ix-flaresolverr-flaresolverr-1
    restart: unless-stopped
    environment:
      NVIDIA_VISIBLE_DEVICES: void
      PORT: '30098'
      LOG_HTML: 'false'
      UMASK: '002'
      TZ: America/Los_Angeles
      UMASK_SET: '002'
      LOG_LEVEL: info
      CAPTCHA_SOLVER: ''
      HOST: 0.0.0.0
      PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      GPG_KEY: ${GPG_KEY}
      PYTHON_VERSION: 3.13.9
      PYTHON_SHA256: ed5ef34cda36cfa2f3a340f07cac7e7814f91c7f3c411f6d3562323a866c5c66
    ports:
    - 30098:30098/tcp
    networks: ix-flaresolverr_default
    healthcheck:
      test:
      - CMD
      - curl
      - --request
      - GET
      - --silent
      - --output
      - /dev/null
      - --show-error
      - --fail
      - http://127.0.0.1:30098/health
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  ix-flaresolverr_default:
    external: true
