services:
  wizarr:
    image: ghcr.io/wizarrrr/wizarr:latest
    container_name: wizarr
    depends_on:
      - wizarr_postgres
      - wizarr_redis
      - wizarr_memcached
    ports:
      - "5690:5690"
    environment:
      # General
      TZ: "America/Los_Angeles"
      WIZARR_ENV: "production"
      WIZARR_LOG_LEVEL: "log"           # verbose|debug|log|warn|error

      # App port inside container
      WIZARR_PORT: "5690"

      # Storage paths
      DB_DIR: "/data/database"
      STORAGE_DIR: "/data/storage"

      # Postgres DB
      DB_HOSTNAME: "wizarr_postgres"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: changeme             # keep this secure
      DB_NAME: "wizarr"
      DB_TYPE: "postgres"

    volumes:
      - /path/to/your/data:/data/database
      - /path/to/your/data:/data/storage

    restart: unless-stopped
    

  wizarr_postgres:
    image: postgres:16-alpine
    container_name: wizarr_postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: changeme   # keep secure
      POSTGRES_DB: "wizarr"
      TZ: "America/Los_Angeles"
    volumes:
      - /path/to/your/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    

  wizarr_redis:
    image: redis:7-alpine
    container_name: wizarr_redis
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    

  wizarr_memcached:
    image: memcached:1.6-alpine
    container_name: wizarr_memcached
    command: ["-m", "64"]
    restart: unless-stopped