version: '3.9'
services:
  bitmagnet-worker:
    image: ghcr.io/bitmagnet-io/bitmagnet:latest
    container_name: bitmagnet-worker
    restart: unless-stopped
    environment:
      POSTGRES_DSN: postgres://bitmagnet:${USER_EMAIL}:5432/bitmagnet?sslmode=disable
      TZ: America/Los_Angeles
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
    - ${DATA_PATH}:/config:rw
    - ${DATA_PATH}:/data:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  bitmagnet-process:
    image: ghcr.io/bitmagnet-io/bitmagnet:latest
    container_name: bitmagnet-process
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      BITMAGNET__HTTP__ENABLED: 'true'
      BITMAGNET__HTTP__ADDR: 0.0.0.0:3333
      POSTGRES_DSN: postgres://bitmagnet:${USER_EMAIL}:5432/bitmagnet?sslmode=disable
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
    - ${DATA_PATH}:/config:rw
    - ${DATA_PATH}:/data:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks: {}
