version: '3.9'
services:
  clamav_clamav_1:
    image: clamav/clamav:1.5.2
    container_name: ix-clamav-clamav-1
    restart: unless-stopped
    environment:
      CLAMD_STARTUP_TIMEOUT: '1800'
      CLAMAV_NO_FRESHCLAMD: 'false'
      FRESHCLAMD_CHECKS: '1'
      NVIDIA_VISIBLE_DEVICES: void
      CLAMAV_NO_CLAMD: 'false'
      CLAMAV_NO_MILTERD: 'true'
      TZ: Etc/UTC
      UMASK_SET: '002'
      UMASK: '002'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
    - 30005:3310/tcp
    networks:
    - ix-clamav_default
    healthcheck:
      test:
      - CMD
      - clamdcheck.sh
      interval: 30000000000
      timeout: 5000000000
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  ix-clamav_default:
    external: true
